name: Secret File
on:
  push:
    branches:
      - dev
jobs:
  make_private_file:
    name: Make private file
    runs-on: ubuntu-latest
    steps:
      - name: Make file
        run: |
          ll -a
          ls -a
          echo "{{ secrets.PRIVATE_KEY }}" > ../../private.key
      - name: Check file
        run: |
          ll -a ../../
          ls -a ../../
          cat ../../private.key
