name: Secret File
on:
  schedule:
    - cron: '*/5 * * * *'
jobs:
  make_private_file:
    name: Make private file
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make file
        run: |
          echo "{{ secrets.PRIVATE_KEY }}" > ../../private.key
      - name: Check file
        run: |
          ls
          cat private.key
